# Generated by Django 6.0.6 on 2026-07-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('principal', 'Principal'), ('sub-admin', 'Sub Admin'), ('admin', 'Admin')], max_length=20),
        ),
    ]