# Generated by Django 6.0.6 on 2026-07-09 09:44

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('principal', 'Principal'), ('sub-admin', 'Sub Admin'), ('admin', 'Admin')], default='teacher', max_length=20),
        ),
    ]
