# Generated by Django 6.0.6 on 2026-06-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_rename_dob_bs_teacher_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='appointmentLetter',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='citizenship',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teachingLicense',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='transcript',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
