# Generated by Django 6.0.7 on 2026-07-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_teacher_reviewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='schoolEmisCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]