# Generated by Django 6.0.7 on 2026-07-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_teacher_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='extraordinaryLeaveRemaining',
            field=models.PositiveIntegerField(default=0),
        ),
    ]