# Generated by Django 6.0.7 on 2026-07-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_backfill_extraordinaryleaveremaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male / पुरुष'), ('female', 'Female / महिला'), ('other', 'Other / अन्य')], default='', max_length=10),
        ),
    ]