# Generated by Django 6.0.7 on 2026-07-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_teacher_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='nameEnglish',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]