# Generated by Django 6.0.7 on 2026-07-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_teacher_nameenglish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='grade',
            field=models.CharField(blank=True, choices=[('first', 'First / प्रथम'), ('second', 'Second / द्वितीय'), ('third', 'Third / तृतीय')], max_length=100, null=True),
        ),
    ]