# Generated by Django 6.0.7 on 2026-07-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_alter_teacher_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='transcript',
        ),
        migrations.AddField(
            model_name='teacher',
            name='highestQualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='minQualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]