# Generated by Django 6.0.7 on 2026-07-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_remove_teacher_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='highestQualificationDocument',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='permanentAppointmentDate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='promotionDate2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='wasDifferentTypeBeforePermanent',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]