# Generated by Django 6.0.7 on 2026-07-26 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_seed_public_school_reference'),
        ('teachers', '0013_teacher_highestqualificationdocument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.CheckConstraint(condition=models.Q(('citizenship__isnull', False), models.Q(('citizenship', ''), _negated=True)), name='teacher_citizenship_required'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.CheckConstraint(condition=models.Q(('degree__isnull', False), models.Q(('degree', ''), _negated=True)), name='teacher_degree_required'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.CheckConstraint(condition=models.Q(('teachingLicense__isnull', False), models.Q(('teachingLicense', ''), _negated=True)), name='teacher_teachingLicense_required'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.CheckConstraint(condition=models.Q(('appointmentLetter__isnull', False), models.Q(('appointmentLetter', ''), _negated=True)), name='teacher_appointmentLetter_required'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.CheckConstraint(condition=models.Q(('appointmentDate__isnull', False), models.Q(('appointmentDate', ''), _negated=True)), name='teacher_appointmentDate_required'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('teacherType', 'permanent'), _negated=True), models.Q(('extraordinaryLeave__isnull', False), models.Q(('extraordinaryLeave', ''), _negated=True)), _connector='OR'), name='teacher_extraordinaryLeave_required_if_permanent'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('teacherType', 'permanent'), _negated=True), models.Q(('wasDifferentTypeBeforePermanent', True), _negated=True), models.Q(('permanentAppointmentDate__isnull', False), models.Q(('permanentAppointmentDate', ''), _negated=True)), _connector='OR'), name='teacher_permanentAppointmentDate_required_if_was_different'),
        ),
    ]