# Generated by Django 6.0.7 on 2026-07-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0015_backfill_school_by_emis_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjectEnglish',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
