# Generated by Django 6.0.7 on 2026-07-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0016_teacher_subjectenglish'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='seeSlcCertificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
