# Generated by Django 6.0.7 on 2026-08-25 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_school_lower_sec_temporary_and_more'),
        ('teachers', '0017_teacher_seeslccertificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='isSpeciallyPromoted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='specialPromotionDate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('isSpeciallyPromoted', True), _negated=True), models.Q(('specialPromotionDate__isnull', False), models.Q(('specialPromotionDate', ''), _negated=True)), _connector='OR'), name='teacher_specialPromotionDate_required_if_specially_promoted'),
        ),
    ]
