# Generated by Django 6.0.6 on 2026-06-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emis_code', models.CharField(max_length=50, unique=True)),
                ('school_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('established_bs', models.CharField(max_length=20)),
                ('permission_date_bs', models.CharField(blank=True, max_length=20, null=True)),
                ('bal_kaksha', models.CharField(blank=True, max_length=20, null=True)),
                ('primary_1_5', models.CharField(blank=True, max_length=20, null=True)),
                ('lower_secondary_6_8', models.CharField(blank=True, max_length=20, null=True)),
                ('secondary_9_10', models.CharField(blank=True, max_length=20, null=True)),
                ('secondary_11_12', models.CharField(blank=True, max_length=20, null=True)),
                ('computer_lab', models.BooleanField(default=False)),
                ('science_lab', models.BooleanField(default=False)),
                ('library', models.BooleanField(default=False)),
                ('book_corner', models.BooleanField(default=False)),
                ('playground', models.BooleanField(default=False)),
                ('land_area', models.FloatField(default=0)),
                ('land_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('building_count', models.IntegerField(default=0)),
                ('classroom_count', models.IntegerField(default=0)),
                ('female_toilets', models.IntegerField(default=0)),
                ('male_toilets', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
