# Generated by Django 6.0.7 on 2026-07-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_principal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='land_area',
        ),
        migrations.RemoveField(
            model_name='school',
            name='land_unit',
        ),
        migrations.AddField(
            model_name='school',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='land_aana',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='land_bigha',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='land_daan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='land_dhur',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='land_kattha',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='land_paisa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='land_ropani',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='land_sqm',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='land_unit_system',
            field=models.CharField(blank=True, choices=[('metric', 'Square Meter'), ('ropani', 'Ropani-Aana-Paisa-Daan'), ('bigha', 'Bigha-Kattha-Dhur')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='municipality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='ward_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]