# Generated by Django 6.0.7 on 2026-07-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_remove_school_land_area_remove_school_land_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicSchoolReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emis_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('school_name', models.CharField(max_length=255)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('municipality', models.CharField(blank=True, default='', max_length=100)),
                ('ward_no', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'ordering': ['school_name'],
            },
        ),
    ]