"""Seeds PublicSchoolReference with the government-registered *Public*
schools list for Kaski district (school year 2083 BS), sourced from the
client-provided file 'school_bibarA_Kaski_2083.xlsx' (sheet
'Students_Level_Report_Under_Gan'). Only rows with SchoolType == 'Public'
were kept (348 of 595 total rows; 239 Private and 8 Religious schools
excluded, as this table is Public-schools-only per the client's request).

Source: client-supplied file school_bibarA_Kaski_2083.xlsx, columns
SchoolCode / SchoolName / District / Local Level / Ward / SchoolType.
"""
from django.db import migrations

RECORDS = [
    {"emis_code": '400010001', "school_name": 'ARWA VIJAYA SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '13'},
    {"emis_code": '400010002', "school_name": 'BIJAYA BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '13'},
    {"emis_code": '400010004', "school_name": 'RATANPANDE SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '13'},
    {"emis_code": '400010006', "school_name": 'Shimala Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '13'},
    {"emis_code": '400010007', "school_name": 'AMAR JYOTI BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '13'},
    {"emis_code": '400010008', "school_name": 'Siddhartha Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '13'},
    {"emis_code": '400020001', "school_name": 'SHANTI SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '16'},
    {"emis_code": '400020002', "school_name": 'GYAN JYOTI SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '16'},
    {"emis_code": '400020003', "school_name": 'ANNAPURNA SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '16'},
    {"emis_code": '400020004', "school_name": 'Nirmal Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '16'},
    {"emis_code": '400020005', "school_name": 'Janata Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '16'},
    {"emis_code": '400020006', "school_name": 'Jhuprangkot Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '16'},
    {"emis_code": '400020007', "school_name": 'SITA BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '16'},
    {"emis_code": '400020008', "school_name": 'Hari Siddhi Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '16'},
    {"emis_code": '400020009', "school_name": 'Shree Narayani Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '16'},
    {"emis_code": '400020010', "school_name": 'Jyoti Bhawan Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '16'},
    {"emis_code": '400030001', "school_name": 'Devi Basic  School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '10'},
    {"emis_code": '400030002', "school_name": 'Dipendra Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '10'},
    {"emis_code": '400030003', "school_name": 'Jana Mandir Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '10'},
    {"emis_code": '400030004', "school_name": 'Bishwo Jyoti Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '10'},
    {"emis_code": '400030005', "school_name": 'Sewa Milan Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '10'},
    {"emis_code": '400030006', "school_name": 'Jana Kalyan Secondary School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '10'},
    {"emis_code": '400040001', "school_name": 'Siddha Baraha Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '23'},
    {"emis_code": '400040004', "school_name": 'Setu Barahi Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '23'},
    {"emis_code": '400040005', "school_name": 'HARPANKOT SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '23'},
    {"emis_code": '400040006', "school_name": 'JANASIDDHA BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '23'},
    {"emis_code": '400040007', "school_name": 'BAHADURE SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '4'},
    {"emis_code": '400050001', "school_name": 'BHULBHULA COMMUNITY BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '33'},
    {"emis_code": '400050002', "school_name": 'KALIKA SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '33'},
    {"emis_code": '400050003', "school_name": 'CHANDI SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '33'},
    {"emis_code": '400050004', "school_name": 'SHISHU KALYAN SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '33'},
    {"emis_code": '400050005', "school_name": 'Bhagawati Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '33'},
    {"emis_code": '400050006', "school_name": 'Gyan Jyoti Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '33'},
    {"emis_code": '400050007', "school_name": 'SUKLA GANDAKI BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '33'},
    {"emis_code": '400050008', "school_name": 'Nawa Jyoti Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '33'},
    {"emis_code": '400050010', "school_name": 'SHANTI UDAYA SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '33'},
    {"emis_code": '400050011', "school_name": 'JANA JYOTI BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '33'},
    {"emis_code": '400050012', "school_name": 'Chirshanti Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '33'},
    {"emis_code": '400050013', "school_name": 'JANAJAGRITI BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '33'},
    {"emis_code": '400050014', "school_name": 'SARASWOTI TIKA SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '33'},
    {"emis_code": '400050015', "school_name": 'Bramha Jyoti basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '33'},
    {"emis_code": '400060001', "school_name": 'PANCHAKOSI BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '23'},
    {"emis_code": '400060003', "school_name": 'Chapakot Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '23'},
    {"emis_code": '400060004', "school_name": 'Phewa Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '23'},
    {"emis_code": '400060005', "school_name": 'SIDDHA BARAHA SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '23'},
    {"emis_code": '400060006', "school_name": 'Pipaldali Deurali Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '23'},
    {"emis_code": '400060007', "school_name": 'Janmabhumi Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '23'},
    {"emis_code": '400060008', "school_name": 'Makanna Devi Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '23'},
    {"emis_code": '400070001', "school_name": 'Sharada Basic School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '9'},
    {"emis_code": '400070002', "school_name": 'Bidya Jyoti Basic School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '8'},
    {"emis_code": '400070003', "school_name": 'Bankot  Basic  School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '8'},
    {"emis_code": '400070004', "school_name": 'Komache Baraha Basic School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '8'},
    {"emis_code": '400070005', "school_name": 'Bhume Basic School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '9'},
    {"emis_code": '400070006', "school_name": 'Birethanti Secondary school', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '8'},
    {"emis_code": '400070007', "school_name": 'Bhagawati secondary school', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '9'},
    {"emis_code": '400070008', "school_name": 'Ulleri Basic School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '9'},
    {"emis_code": '400070009', "school_name": 'Rampyaro Basic School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '8'},
    {"emis_code": '400070010', "school_name": 'uma secondary school', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '8'},
    {"emis_code": '400070012', "school_name": 'Modi Basic School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '8'},
    {"emis_code": '400080001', "school_name": 'Birendra basic school', "district": 'Kaski', "municipality": 'Rupa Rural Municipality', "ward_no": '5'},
    {"emis_code": '400080003', "school_name": 'Gaun Pharka Basic School', "district": 'Kaski', "municipality": 'Rupa Rural Municipality', "ward_no": '5'},
    {"emis_code": '400080004', "school_name": 'Bhairawi Basic School', "district": 'Kaski', "municipality": 'Rupa Rural Municipality', "ward_no": '5'},
    {"emis_code": '400080005', "school_name": 'Bishwa Shanti Secondary School', "district": 'Kaski', "municipality": 'Rupa Rural Municipality', "ward_no": '5'},
    {"emis_code": '400090001', "school_name": 'Janapriya Basic School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '7'},
    {"emis_code": '400090002', "school_name": 'Gyanodaya Basic School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '7'},
    {"emis_code": '400090004', "school_name": 'Deurali Basic School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '7'},
    {"emis_code": '400090005', "school_name": 'Udaya Secondary  School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '7'},
    {"emis_code": '400090006', "school_name": 'Prithivi Narayan Secondary School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '7'},
    {"emis_code": '400100002', "school_name": 'Laxmi Basic School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '3'},
    {"emis_code": '400100003', "school_name": 'Saraswati  Basic School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '2'},
    {"emis_code": '400100004', "school_name": 'Bal Jyoti Basic School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '3'},
    {"emis_code": '400100005', "school_name": 'Lahari basic school', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '1'},
    {"emis_code": '400100006', "school_name": 'Mahendra  Basic School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '1'},
    {"emis_code": '400100007', "school_name": 'Durga Bhawani Adarsha Basic School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '2'},
    {"emis_code": '400100008', "school_name": 'Machhapuchhre secondary school', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '2'},
    {"emis_code": '400100009', "school_name": 'Parashu Basic School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '1'},
    {"emis_code": '400100010', "school_name": 'DHARAPANI SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '3'},
    {"emis_code": '400100013', "school_name": 'SIRJANA COMMUNITY SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '1'},
    {"emis_code": '400100014', "school_name": 'Shree Paundur Basic School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '3'},
    {"emis_code": '400100015', "school_name": 'BalMandir secondary school', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '3'},
    {"emis_code": '400110001', "school_name": 'Baraha  Secondary School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '6'},
    {"emis_code": '400110002', "school_name": 'Bhoomeshwor Secondary School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '6'},
    {"emis_code": '400110003', "school_name": 'Jana Kalyan Basic School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '6'},
    {"emis_code": '400110006', "school_name": 'Indreni Basic school', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '6'},
    {"emis_code": '400110007', "school_name": 'Bhumeshwor Basic School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '6'},
    {"emis_code": '400110009', "school_name": 'Kailash Tetsuo Basic School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '6'},
    {"emis_code": '400120001', "school_name": 'Megha Raj Basic School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '3'},
    {"emis_code": '400120002', "school_name": 'Bal Kalyan Basic School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '3'},
    {"emis_code": '400120003', "school_name": 'Shukla Gandaki secondary School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '3'},
    {"emis_code": '400120005', "school_name": 'Janajagaran Namuna Samudayik  Basic School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '3'},
    {"emis_code": '400130001', "school_name": 'Kurlung Baraha Basic School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '10'},
    {"emis_code": '400130003', "school_name": 'Janasewa basic school', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '10'},
    {"emis_code": '400130004', "school_name": 'Tal Barahi Basic School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '11'},
    {"emis_code": '400130005', "school_name": 'Mai Sewa Basic School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '10'},
    {"emis_code": '400130006', "school_name": 'SHREE JANAPREMI BASIC SCHOOL', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '10'},
    {"emis_code": '400130007', "school_name": 'Saraswati Basic School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '11'},
    {"emis_code": '400130009', "school_name": 'Ghurjung Basic School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '11'},
    {"emis_code": '400130010', "school_name": 'Phumrokhun Baraha  Secondary School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '10'},
    {"emis_code": '400130011', "school_name": 'Shree Meshram Baraha Secondary School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '10'},
    {"emis_code": '400140002', "school_name": 'Basundhara Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '12'},
    {"emis_code": '400140003', "school_name": 'Deurali Basic School', "district": 'Kaski', "municipality": 'Rupa Rural Municipality', "ward_no": '7'},
    {"emis_code": '400140004', "school_name": 'Indrayani Basic School', "district": 'Kaski', "municipality": 'Rupa Rural Municipality', "ward_no": '7'},
    {"emis_code": '400140006', "school_name": 'Saraswati  Basic School', "district": 'Kaski', "municipality": 'Rupa Rural Municipality', "ward_no": '7'},
    {"emis_code": '400140008', "school_name": 'Arunodaya Basic School', "district": 'Kaski', "municipality": 'Rupa Rural Municipality', "ward_no": '7'},
    {"emis_code": '400140011', "school_name": 'Himalaya Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '12'},
    {"emis_code": '400140013', "school_name": 'Ramkot Secondary School', "district": 'Kaski', "municipality": 'Rupa Rural Municipality', "ward_no": '7'},
    {"emis_code": '400150001', "school_name": 'Gauri Shankar Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '25'},
    {"emis_code": '400150002', "school_name": 'Bal Kalyan Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '25'},
    {"emis_code": '400150006', "school_name": 'Divya Jyoti Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '25'},
    {"emis_code": '400150008', "school_name": 'AMBIKA SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '25'},
    {"emis_code": '400150009', "school_name": 'GAURI SHANKAR SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '25'},
    {"emis_code": '400150010', "school_name": 'BISHNU PADUKA SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '25'},
    {"emis_code": '400150019', "school_name": 'Vikramshila Buddhist Bidya Sasthan Basic Level', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '25'},
    {"emis_code": '400150020', "school_name": 'Gauri Shankar Multiple Campus', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '25'},
    {"emis_code": '400160002', "school_name": 'KALIKA SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '11'},
    {"emis_code": '400160003', "school_name": 'KAHUN BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '11'},
    {"emis_code": '400160004', "school_name": 'Karma Siddha Parampara Aadharbhut Gumba', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '11'},
    {"emis_code": '400170001', "school_name": 'Chandika Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '5'},
    {"emis_code": '400170002', "school_name": 'Himalaya Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '5'},
    {"emis_code": '400170003', "school_name": 'Bamchandrakala Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '5'},
    {"emis_code": '400170009', "school_name": 'JANA JYOTI SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '28'},
    {"emis_code": '400170010', "school_name": 'Bidhya Jyoti Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '5'},
    {"emis_code": '400170011', "school_name": 'Siddha Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '28'},
    {"emis_code": '400170012', "school_name": 'Lekhnath Basic school', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '28'},
    {"emis_code": '400180001', "school_name": 'Sadashiva Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '24'},
    {"emis_code": '400180002', "school_name": 'Matri Bhumi Jana Prakash Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '24'},
    {"emis_code": '400180003', "school_name": 'BIJAY BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '24'},
    {"emis_code": '400180004', "school_name": 'Basanta Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '24'},
    {"emis_code": '400180005', "school_name": 'Bal Prabodhini Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '24'},
    {"emis_code": '400180006', "school_name": 'Saraswati Kunja Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '24'},
    {"emis_code": '400180007', "school_name": 'KALIKA SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '24'},
    {"emis_code": '400180008', "school_name": 'SIDDHA BARAHA BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '24'},
    {"emis_code": '400180009', "school_name": 'PAME BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '24'},
    {"emis_code": '400190002', "school_name": 'Ramadi Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '21'},
    {"emis_code": '400190003', "school_name": 'Bal Kalyan Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '21'},
    {"emis_code": '400190004', "school_name": 'Bayali Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '21'},
    {"emis_code": '400190006', "school_name": 'BAL JYOTI BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '21'},
    {"emis_code": '400190007', "school_name": 'Dhuwarkot Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '21'},
    {"emis_code": '400190008', "school_name": 'YUBA BARSHA BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '21'},
    {"emis_code": '400190009', "school_name": 'Bakrek Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '21'},
    {"emis_code": '400190012', "school_name": 'BHABISHYA NIRMAN SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '21'},
    {"emis_code": '400200002', "school_name": 'Jana Kalyan Basic School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '4'},
    {"emis_code": '400200004', "school_name": 'Mahendra Secondary School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '4'},
    {"emis_code": '400200006', "school_name": 'Jana Jagaran Basic School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '4'},
    {"emis_code": '400200007', "school_name": 'Deurali Basic School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '4'},
    {"emis_code": '400210001', "school_name": 'Akala Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '19'},
    {"emis_code": '400210003', "school_name": 'Shree Gayatri Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '19'},
    {"emis_code": '400210004', "school_name": 'Bhumeshwor Primary School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '19'},
    {"emis_code": '400210005', "school_name": 'MAHENDRA SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '19'},
    {"emis_code": '400220002', "school_name": 'AMARJYOTI GAUNPHARK SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '26'},
    {"emis_code": '400220003', "school_name": 'Arun Jyoti Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '31'},
    {"emis_code": '400220005', "school_name": 'Sita Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '32'},
    {"emis_code": '400220008', "school_name": 'Bishwo Jyoti Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '31'},
    {"emis_code": '400220009', "school_name": 'Jaladhar Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '31'},
    {"emis_code": '400220010', "school_name": 'Indrani Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '31'},
    {"emis_code": '400220011', "school_name": 'Nawa Durga Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '29'},
    {"emis_code": '400220012', "school_name": 'KALIKA BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '32'},
    {"emis_code": '400220013', "school_name": 'SHIVA SHAKTI BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '26'},
    {"emis_code": '400220014', "school_name": 'PATNYARI BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '29'},
    {"emis_code": '400220015', "school_name": 'Chandra Jyoti Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '32'},
    {"emis_code": '400220016', "school_name": 'Tarun Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '27'},
    {"emis_code": '400220017', "school_name": 'Siddha Ganesh Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '32'},
    {"emis_code": '400220018', "school_name": 'BIR BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '27'},
    {"emis_code": '400220019', "school_name": 'Kalyan Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '27'},
    {"emis_code": '400220020', "school_name": 'Kabishiromani Lekhanath Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '27'},
    {"emis_code": '400220021', "school_name": 'AMAR JYOTI BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '26'},
    {"emis_code": '400220022', "school_name": 'RADHAKRISHNA GURUKUL SANSKRIT VIDYALAYA', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '32'},
    {"emis_code": '400220023', "school_name": 'SHANTI BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '30'},
    {"emis_code": '400220024', "school_name": 'NAWAJYOTI SANATDURGA BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '30'},
    {"emis_code": '400220025', "school_name": 'RAMJYOTI SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '26'},
    {"emis_code": '400220026', "school_name": 'TRIBHUBHAN SHANTI SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '30'},
    {"emis_code": '400220027', "school_name": 'BHAWANI KALIKA SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '26'},
    {"emis_code": '400220028', "school_name": 'BRAHMHARUPA SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '32'},
    {"emis_code": '400220029', "school_name": 'AMAR SIDDHA NAMUNA SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '31'},
    {"emis_code": '400220030', "school_name": 'GOGAN SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '32'},
    {"emis_code": '400220031', "school_name": 'JANA PRAKASH SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '29'},
    {"emis_code": '400220032', "school_name": 'ANANDA JYOTI SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '31'},
    {"emis_code": '400220033', "school_name": 'LAXMI SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '26'},
    {"emis_code": '400220034', "school_name": 'LAXMI ADARSHA SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '27'},
    {"emis_code": '400220035', "school_name": 'SIRJANA RESIDENTIAL SECONDARY SCHOOL FOR THE DEAF', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '26'},
    {"emis_code": '400220058', "school_name": 'HIMALAYA BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '32'},
    {"emis_code": '400230001', "school_name": 'Chandi basic school', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '7'},
    {"emis_code": '400230002', "school_name": 'Himalaya Secondary School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '7'},
    {"emis_code": '400230003', "school_name": 'Landruk Basic School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '7'},
    {"emis_code": '400230005', "school_name": 'Himalaya Basic School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '7'},
    {"emis_code": '400230006', "school_name": 'Tanchok Basic School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '7'},
    {"emis_code": '400230008', "school_name": 'Gyanodaya Basic School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '6'},
    {"emis_code": '400230009', "school_name": 'Sangam secondary school', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '6'},
    {"emis_code": '400240002', "school_name": 'Tarebaraha Basic School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '8'},
    {"emis_code": '400240003', "school_name": 'Bom Bahadur Ghalel Basic School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '8'},
    {"emis_code": '400240004', "school_name": 'HimGiri Basic School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '8'},
    {"emis_code": '400240005', "school_name": 'Barahi Basic School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '8'},
    {"emis_code": '400240006', "school_name": 'Annapurna Basic School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '8'},
    {"emis_code": '400240007', "school_name": 'Shaheed Hariprasad Basic School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '8'},
    {"emis_code": '400240008', "school_name": 'Saraswati Basic School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '9'},
    {"emis_code": '400240009', "school_name": 'Janata Basic School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '8'},
    {"emis_code": '400240010', "school_name": 'Gaurishankar Manilal  Secondary School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '9'},
    {"emis_code": '400250001', "school_name": 'Himali Pra V', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '1'},
    {"emis_code": '400250002', "school_name": 'Himalaya Danfe Basic School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '1'},
    {"emis_code": '400250004', "school_name": 'Annapurna Basic School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '1'},
    {"emis_code": '400250005', "school_name": 'Sharada Secondary School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '1'},
    {"emis_code": '400260004', "school_name": 'Bhurtel Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '28'},
    {"emis_code": '400260005', "school_name": 'Bishwo Jyoti Basic school', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '12'},
    {"emis_code": '400260006', "school_name": 'RATNA SHOVA SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '28'},
    {"emis_code": '400260007', "school_name": 'Bhagawati Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '12'},
    {"emis_code": '400270002', "school_name": 'GYANODAYA RAGHU BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '20'},
    {"emis_code": '400270004', "school_name": 'Saraswati Birmaya Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '20'},
    {"emis_code": '400270005', "school_name": 'Shree Sita Basic school', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '20'},
    {"emis_code": '400270006', "school_name": 'HIMALAYA SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '20'},
    {"emis_code": '400280001', "school_name": 'Nawa Prabhat Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '8'},
    {"emis_code": '400280003', "school_name": 'Saraswati Kunj Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '9'},
    {"emis_code": '400280004', "school_name": 'Deep Jyoti Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '8'},
    {"emis_code": '400280005', "school_name": 'Ganga Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '9'},
    {"emis_code": '400280006', "school_name": 'Pragati Sadan Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '9'},
    {"emis_code": '400280008', "school_name": 'Siddha Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '8'},
    {"emis_code": '400280009', "school_name": 'Shiva Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '8'},
    {"emis_code": '400280010', "school_name": 'Narayan Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '8'},
    {"emis_code": '400280011', "school_name": 'Bal Kalyan Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '9'},
    {"emis_code": '400280012', "school_name": 'Prabhat Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '8'},
    {"emis_code": '400280013', "school_name": 'Himalaya Secondary School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '9'},
    {"emis_code": '400290001', "school_name": 'Himalaya Milan Secondary School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '2'},
    {"emis_code": '400290002', "school_name": 'Narayani  Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '2'},
    {"emis_code": '400290003', "school_name": 'Mahendrodaya Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '2'},
    {"emis_code": '400300003', "school_name": 'Jana Jyoti Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '21'},
    {"emis_code": '400300004', "school_name": 'JANA JAGRITI BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '21'},
    {"emis_code": '400300005', "school_name": 'Bal Bidyashram Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '21'},
    {"emis_code": '400300006', "school_name": 'JANA CHETAN SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '21'},
    {"emis_code": '400310001', "school_name": 'Nalku Pra V', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '1'},
    {"emis_code": '400310002', "school_name": 'Sthanapati basic school', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '1'},
    {"emis_code": '400310003', "school_name": 'Dudh Pokhari Secondary School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '1'},
    {"emis_code": '400310004', "school_name": 'Annapurna Secondary School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '1'},
    {"emis_code": '400320001', "school_name": 'DHARMASTHALI BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '5'},
    {"emis_code": '400320002', "school_name": 'BARAHI SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '5'},
    {"emis_code": '400320005', "school_name": 'Annapurna Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '6'},
    {"emis_code": '400320006', "school_name": 'TAL BARAHI SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '6'},
    {"emis_code": '400320013', "school_name": 'SHREE KRISHNA SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '7'},
    {"emis_code": '400320017', "school_name": 'RAM BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '8'},
    {"emis_code": '400320018', "school_name": 'JANAPRIYA SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '8'},
    {"emis_code": '400320036', "school_name": 'CHHOREPATAN  SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '17'},
    {"emis_code": '400320037', "school_name": 'JANAKI SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '17'},
    {"emis_code": '400320038', "school_name": 'PARDI SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '17'},
    {"emis_code": '400320051', "school_name": 'KUNDAHAR BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '10'},
    {"emis_code": '400320052', "school_name": 'KALIKA SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '10'},
    {"emis_code": '400320062', "school_name": 'SHIVA SHAKTI SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '11'},
    {"emis_code": '400320070', "school_name": 'SHITALADEVI COMMUNITY SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '12'},
    {"emis_code": '400320071', "school_name": 'SARASWOTI BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '12'},
    {"emis_code": '400320075', "school_name": 'AMAR SINGH SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '12'},
    {"emis_code": '400320082', "school_name": 'BHADRAKALI SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '13'},
    {"emis_code": '400320086', "school_name": 'BHAYARESHWORI BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '14'},
    {"emis_code": '400320087', "school_name": 'RAMESHWORI SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '14'},
    {"emis_code": '400320089', "school_name": 'SIDDHA SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '15'},
    {"emis_code": '400320098', "school_name": 'MASINA BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '14'},
    {"emis_code": '400320099', "school_name": 'SHUKRARAJ BALABHADRA SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '14'},
    {"emis_code": '400320101', "school_name": 'RASTRIYA SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '1'},
    {"emis_code": '400320103', "school_name": 'RATNA BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '1'},
    {"emis_code": '400320104', "school_name": 'SANSKRIT SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '1'},
    {"emis_code": '400320113', "school_name": 'BINDHYABASINI SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '2'},
    {"emis_code": '400320116', "school_name": 'GYAN BHOOMI SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '3'},
    {"emis_code": '400320117', "school_name": 'BAL MANDIR SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '3'},
    {"emis_code": '400320118', "school_name": 'KANYA  SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '3'},
    {"emis_code": '400320125', "school_name": 'NAVIN SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '4'},
    {"emis_code": '400320131', "school_name": 'MAHENDRA SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '9'},
    {"emis_code": '400320132', "school_name": 'NAWA PRABHAT SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '9'},
    {"emis_code": '400320133', "school_name": 'SAHARA BAL BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '9'},
    {"emis_code": '400320140', "school_name": 'Divya Jyoti Basic School', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '16'},
    {"emis_code": '400320143', "school_name": 'VINDHYA VASINI SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '16'},
    {"emis_code": '400320150', "school_name": 'INDRA RAJYA LAXMI SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '16'},
    {"emis_code": '400320193', "school_name": 'SIDDHA PAROPAKAR BAIDIK GURUKUL ASHRAM', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '15'},
    {"emis_code": '400320206', "school_name": 'POKHARA NAMUNA BAIKALPIK SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '9'},
    {"emis_code": '400330001', "school_name": 'Anadu basic school', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '22'},
    {"emis_code": '400330002', "school_name": 'CHANDI Basic SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '22'},
    {"emis_code": '400330003', "school_name": 'Kalika Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '22'},
    {"emis_code": '400330004', "school_name": 'Pokhara Darshaniyasthal Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '22'},
    {"emis_code": '400330005', "school_name": 'BHAGAWATI BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '22'},
    {"emis_code": '400330006', "school_name": 'Saraswati basic school', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '22'},
    {"emis_code": '400330007', "school_name": 'MAHESHWORI SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '22'},
    {"emis_code": '400330008', "school_name": 'SHUKRARAJ SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '22'},
    {"emis_code": '400330010', "school_name": 'LAXMI BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '22'},
    {"emis_code": '400330011', "school_name": 'LILA BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '22'},
    {"emis_code": '400330012', "school_name": 'DURGA BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '22'},
    {"emis_code": '400330013', "school_name": 'OKHALEDANDA BHUMDIKOT SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '22'},
    {"emis_code": '400330015', "school_name": 'Yuba Jyoti Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '22'},
    {"emis_code": '400340002', "school_name": 'Himalayan Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '19'},
    {"emis_code": '400340003', "school_name": 'BINDHYESHWORI SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '19'},
    {"emis_code": '400340006', "school_name": 'Dhara Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '19'},
    {"emis_code": '400340007', "school_name": 'Shiveshwori Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '19'},
    {"emis_code": '400340008', "school_name": 'BHARATI BHAWAN SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '19'},
    {"emis_code": '400350002', "school_name": 'Machapuchhre Basic School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '5'},
    {"emis_code": '400350003', "school_name": 'Nispaksha Secondary School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '5'},
    {"emis_code": '400360001', "school_name": 'Sharada  Basic School', "district": 'Kaski', "municipality": 'Rupa Rural Municipality', "ward_no": '6'},
    {"emis_code": '400360002', "school_name": 'Kamal Basic School', "district": 'Kaski', "municipality": 'Rupa Rural Municipality', "ward_no": '6'},
    {"emis_code": '400360003', "school_name": 'Chandra Prabha Secondary School', "district": 'Kaski', "municipality": 'Rupa Rural Municipality', "ward_no": '6'},
    {"emis_code": '400360006', "school_name": 'Rupa Jyoti Secondary School', "district": 'Kaski', "municipality": 'Rupa Rural Municipality', "ward_no": '6'},
    {"emis_code": '400360008', "school_name": 'Prithvi Rupa Secondary School', "district": 'Kaski', "municipality": 'Rupa Rural Municipality', "ward_no": '6'},
    {"emis_code": '400370002', "school_name": 'Shova basic school', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '11'},
    {"emis_code": '400370003', "school_name": 'Annapurna Sitapokhari Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '11'},
    {"emis_code": '400370004', "school_name": 'Rastra Jyoti Secondary School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '11'},
    {"emis_code": '400380001', "school_name": 'Jana Jagriti basic school', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '5'},
    {"emis_code": '400380002', "school_name": 'Salleri Basic School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '4'},
    {"emis_code": '400380003', "school_name": 'Jana Siddha Basic School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '5'},
    {"emis_code": '400380004', "school_name": 'Baraha Basic School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '4'},
    {"emis_code": '400380005', "school_name": 'Bhumeshwor Basic School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '4'},
    {"emis_code": '400380006', "school_name": 'Shitala Community Secondary School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '5'},
    {"emis_code": '400380007', "school_name": 'Pragatishil secondary school', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '4'},
    {"emis_code": '400380010', "school_name": 'Abhiman Memorial Secondary School', "district": 'Kaski', "municipality": 'Annapurna Rural Municipality', "ward_no": '5'},
    {"emis_code": '400390001', "school_name": 'SHANTA SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '18'},
    {"emis_code": '400390002', "school_name": 'JANAJAGRITI SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '18'},
    {"emis_code": '400390004', "school_name": 'Mani Jyoti Adharbhut Vidhyalaya', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '18'},
    {"emis_code": '400390006', "school_name": 'Saraswati Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '18'},
    {"emis_code": '400390007', "school_name": 'Prabhat Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '18'},
    {"emis_code": '400390008', "school_name": 'Srijana Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '18'},
    {"emis_code": '400390009', "school_name": 'Sharada Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '18'},
    {"emis_code": '400390012', "school_name": 'VIDHYA JYOTI SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '18'},
    {"emis_code": '400400002', "school_name": 'Himalaya Tinshir Basic School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '2'},
    {"emis_code": '400400006', "school_name": 'Barahi Basic School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '2'},
    {"emis_code": '400400007', "school_name": 'Krishna Mahadev Basic School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '2'},
    {"emis_code": '400400008', "school_name": 'Machapuchhre Secondary School', "district": 'Kaski', "municipality": 'Machhapuchchhre Rural Municipality', "ward_no": '2'},
    {"emis_code": '400410001', "school_name": 'Mai Maidan Basic School', "district": 'Kaski', "municipality": 'Rupa Rural Municipality', "ward_no": '3'},
    {"emis_code": '400410002', "school_name": 'Kalpa basic school', "district": 'Kaski', "municipality": 'Rupa Rural Municipality', "ward_no": '4'},
    {"emis_code": '400410003', "school_name": 'Mahendra Basic School', "district": 'Kaski', "municipality": 'Rupa Rural Municipality', "ward_no": '4'},
    {"emis_code": '400410004', "school_name": 'Janata Secondary School', "district": 'Kaski', "municipality": 'Rupa Rural Municipality', "ward_no": '3'},
    {"emis_code": '400410005', "school_name": 'Bageshwori Basic School i', "district": 'Kaski', "municipality": 'Rupa Rural Municipality', "ward_no": '3'},
    {"emis_code": '400410007', "school_name": 'Gaunpharka Secondary school', "district": 'Kaski', "municipality": 'Rupa Rural Municipality', "ward_no": '4'},
    {"emis_code": '400420002', "school_name": 'Dhanubas Kalika Secondary School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '7'},
    {"emis_code": '400420005', "school_name": 'Shivashakti Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '6'},
    {"emis_code": '400420006', "school_name": 'Sildu basic school', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '7'},
    {"emis_code": '400420007', "school_name": 'Baraha Pra V', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '7'},
    {"emis_code": '400420008', "school_name": 'Maharudra Secondary School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '6'},
    {"emis_code": '400420009', "school_name": 'Kalika Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '7'},
    {"emis_code": '400420010', "school_name": 'Dhanubas Kalika Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '7'},
    {"emis_code": '400420011', "school_name": 'Bal Padam Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '7'},
    {"emis_code": '400430002', "school_name": 'Dhruva Secondary School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '4'},
    {"emis_code": '400430003', "school_name": 'Sitaram Secondary School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '3'},
    {"emis_code": '400430004', "school_name": 'Binda Basini Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '3'},
    {"emis_code": '400430006', "school_name": 'Mangalodaya Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '3'},
    {"emis_code": '400430007', "school_name": 'Nawa Durga Basic School', "district": 'Kaski', "municipality": 'Madi Rural Municipality', "ward_no": '4'},
    {"emis_code": '400440001', "school_name": 'Rithumala Basic School', "district": 'Kaski', "municipality": 'Rupa Rural Municipality', "ward_no": '1'},
    {"emis_code": '400440002', "school_name": 'Kuleshwor Basic School', "district": 'Kaski', "municipality": 'Rupa Rural Municipality', "ward_no": '2'},
    {"emis_code": '400440005', "school_name": 'Saraswati Basic School', "district": 'Kaski', "municipality": 'Rupa Rural Municipality', "ward_no": '1'},
    {"emis_code": '400440007', "school_name": 'Jateshwor Secondary School', "district": 'Kaski', "municipality": 'Rupa Rural Municipality', "ward_no": '1'},
    {"emis_code": '400440008', "school_name": 'Kalika Secondary School', "district": 'Kaski', "municipality": 'Rupa Rural Municipality', "ward_no": '1'},
    {"emis_code": '400440009', "school_name": 'Shivalaya Secondary School', "district": 'Kaski', "municipality": 'Rupa Rural Municipality', "ward_no": '2'},
    {"emis_code": '400440010', "school_name": 'Chandi Basic School', "district": 'Kaski', "municipality": 'Rupa Rural Municipality', "ward_no": '1'},
    {"emis_code": '400450001', "school_name": 'Devi Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '20'},
    {"emis_code": '400450004', "school_name": 'Mahendra Rastriya Pra V', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '20'},
    {"emis_code": '400450005', "school_name": 'MAHENDRA SECONDARY SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '20'},
    {"emis_code": '400450006', "school_name": 'BHALAM BASIC SCHOOL', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '20'},
    {"emis_code": '400450009', "school_name": 'Shramik Adharbhut Vidyalaya', "district": 'Kaski', "municipality": 'Pokhara Metropolitan City', "ward_no": '25'},]


def seed_public_schools(apps, schema_editor):
    PublicSchoolReference = apps.get_model("schools", "PublicSchoolReference")
    PublicSchoolReference.objects.bulk_create(
        [PublicSchoolReference(**r) for r in RECORDS],
        ignore_conflicts=True,
    )


def unseed_public_schools(apps, schema_editor):
    PublicSchoolReference = apps.get_model("schools", "PublicSchoolReference")
    PublicSchoolReference.objects.filter(
        emis_code__in=[r["emis_code"] for r in RECORDS]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0004_publicschoolreference"),
    ]

    operations = [
        migrations.RunPython(seed_public_schools, unseed_public_schools),
    ]