# Generated by Django 6.0.7 on 2026-07-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_teacher_quota_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='e_library',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='smart_board',
            field=models.BooleanField(default=False),
        ),
    ]
