# Generated by Django 6.0.7 on 2026-07-31 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_school_e_library_school_smart_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='lower_sec_temporary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='pre_primary_temporary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='primary_temporary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='secondary_11_12_temporary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='secondary_9_10_temporary',
            field=models.IntegerField(default=0),
        ),
    ]