# Generated by Django 6.0.7 on 2026-07-18 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0007_teacher_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_np', models.CharField(blank=True, help_text='Nepali label shown alongside the English name, e.g. बिरामी बिदा.', max_length=100, null=True)),
                ('annual_quota_days', models.PositiveIntegerField(help_text='Days allowed per calendar year for this leave type.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive types are hidden from the teacher-facing apply form but kept for historical records.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_count', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('document', models.FileField(upload_to='leave_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='teachers.teacher')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='leaves.leavetype')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]