# Generated by Django 6.0.7 on 2026-07-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_seed_leave_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_lifetime',
            field=models.BooleanField(default=False, help_text='True for career-long leave types (e.g. Extraordinary Leave) whose quota does NOT reset every year -- annual_quota_days is instead an absolute career cap, and usage is summed across every year rather than the current one. See leaves/views.py, and note Extraordinary Leave specifically draws its per-teacher remaining balance from Teacher.extraordinaryLeaveRemaining rather than this shared annual_quota_days value.'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='annual_quota_days',
            field=models.PositiveIntegerField(help_text='Days allowed per calendar year for this leave type (or the lifetime cap, if is_lifetime).'),
        ),
    ]