# Generated by Django 6.0.7 on 2026-07-23 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('teachers', '0011_teacher_nameenglish'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_school_name', models.CharField(blank=True, default='', max_length=255)),
                ('old_school_emis_code', models.CharField(blank=True, default='', max_length=50)),
                ('old_district', models.CharField(blank=True, default='', max_length=100)),
                ('old_municipality', models.CharField(blank=True, default='', max_length=100)),
                ('old_ward_no', models.CharField(blank=True, default='', max_length=10)),
                ('new_school_name', models.CharField(max_length=255)),
                ('new_school_emis_code', models.CharField(max_length=50)),
                ('new_school_address', models.TextField(blank=True, default='')),
                ('new_district', models.CharField(max_length=100)),
                ('new_municipality', models.CharField(max_length=100)),
                ('new_ward_no', models.CharField(max_length=10)),
                ('transfer_document', models.FileField(upload_to='transfer_requests/')),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, default='', max_length=255)),
                ('new_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfer_requests', to='schools.school')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_transfer_requests', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]