# Generated by Django 6.0.7 on 2026-07-24 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('teachers', '0011_teacher_nameenglish'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherTransferDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='transfer_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_documents', to='teachers.teacher')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]