# Generated by Django 6.0.7 on 2026-07-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_teachertransferdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchangerequest',
            name='document_type',
            field=models.CharField(choices=[('citizenship', 'Citizenship'), ('degree', 'Degree Certificate'), ('photo', 'Passport Size Photo'), ('teachingLicense', 'Teaching License'), ('appointmentLetter', 'Appointment Letter'), ('highestQualificationDocument', 'Highest Qualification Document')], max_length=30),
        ),
    ]