# Generated by Django 6.0.7 on 2026-07-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_documentchangerequest_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchangerequest',
            name='document_type',
            field=models.CharField(choices=[('citizenship', 'Citizenship'), ('degree', 'Degree Certificate'), ('photo', 'Passport Size Photo'), ('teachingLicense', 'Teaching License'), ('appointmentLetter', 'Appointment Letter'), ('highestQualificationDocument', 'Highest Qualification Document'), ('seeSlcCertificate', 'SEE/SLC Certificate')], max_length=30),
        ),
    ]
